import type { Guide } from "./types"

export const guide: Guide = {
  slug: "digital-meny-kompletta-guiden",
  title: "Digital meny för restaurang — kompletta guiden",
  metaTitle: "Digital meny för restaurang — kompletta guiden 2026",
  description:
    "Allt du behöver veta om digital meny 2026: hur den fungerar, vad den kostar, vad lagen kräver om allergener, och hur du väljer rätt lösning för din restaurang.",
  datePublished: "2026-08-26",
  dateModified: "2026-08-26",
  readingMinutes: 14,
  category: "Grundguide",
  intro: [
    "En **digital meny** är en restaurangmeny som gästen läser på en skärm i stället för på papper — i praktiken oftast i sin egen mobil, via en QR-kod på bordet. I sin enklaste form ersätter den det tryckta menykortet; i sin mest utbyggda form låter den gästen både bläddra, filtrera på allergener och beställa direkt från bordet.",
    "Den här guiden är skriven för dig som driver restaurang, café, pizzeria eller bar i Sverige och funderar på att gå över till digital meny — eller byta lösning. Vi går igenom hur tekniken fungerar, vad den faktiskt kostar, vad livsmedelslagstiftningen kräver, och vilka fällor du bör undvika. Guiden uppdateras löpande.",
  ],
  tldr: [
    "En digital meny visas i gästens mobil via QR-kod — ingen app behöver laddas ned och inga menyskärmar behöver köpas in.",
    "Priset ligger typiskt på några hundralappar i månaden som fast kostnad. [Servera](/priser) börjar på 549 kr/mån utan provision per beställning.",
    "En tryckt A4-meny kostar från ca 2,40–6 kr per exemplar hos svenska tryckerier — och blir inaktuell vid varje pris- eller menyändring. En digital meny uppdateras på sekunder.",
    "Allergeninformation är obligatorisk för all oförpackad mat enligt EU-förordning 1169/2011. Informationen får ges muntligt, men det måste tydligt framgå hur gästen får tag på den — en digital meny kan visa den direkt vid varje rätt.",
    "Välj lösning efter tre frågor: Vill du bara visa menyn eller också ta emot beställningar? Behöver du flera språk? Vill du slippa provision per order?",
  ],
  blocks: [
    { t: "h2", id: "hur-fungerar-det", text: "Hur fungerar en digital meny i praktiken?" },
    { t: "p", text: "Grundflödet är detsamma i nästan alla moderna lösningar. Du lägger in kategorier, rätter, priser, bilder och allergenmärkning i en adminpanel. Systemet genererar sedan en QR-kod — antingen en gemensam för hela restaurangen eller en unik kod per bord. Gästen riktar mobilkameran mot koden, menyn öppnas direkt i webbläsaren, och i system med beställningsfunktion skickas gästens order till en köksskärm." },
    { t: "p", text: "Det viktiga ordet är **webbläsaren**. Kring 2018–2020 byggde många aktörer app-baserade lösningar där gästen först skulle ladda ned en app och skapa konto. Det ledde till att en stor andel gäster gav upp innan de ens sett menyn. Dagens standard i Sverige är app-fritt: skanna, titta, klart. Om en leverantör kräver app-nedladdning av dina gäster är det i sig ett skäl att titta vidare." },
    { t: "p", text: "För restaurangen består systemet typiskt av tre delar: en **gästvy** (menyn som öppnas via QR-koden), en **köks- eller personalvy** (inkommande beställningar och bordsstatus) och en **adminpanel** (menyredigering, priser, öppettider, statistik). I [Servera](/funktioner) finns dessutom en servitörsvy där personalen ser vilka bord som behöver hjälp." },
    { t: "h2", id: "typer", text: "Vilka typer av digitala menyer finns det?" },
    { t: "p", text: "Begreppet används om ganska olika saker, och det är lätt att jämföra äpplen med päron när man tar in offerter. De fyra vanligaste varianterna:" },
    { t: "table", head: ["Typ", "Vad det är", "Passar bäst för"], rows: [
      ["PDF bakom QR-kod", "En inskannad eller exporterad PDF av den tryckta menyn", "Tillfälliga lösningar — men zoomande och nypande i en PDF på mobil är en dålig gästupplevelse"],
      ["Webbmeny (visning)", "En riktig mobilanpassad meny med kategorier, bilder och allergenfilter — utan beställning", "Restauranger med bordsservering som vill behålla beställning via personal"],
      ["Webbmeny + beställning", "Gästen beställer och betalar direkt från bordet; ordern går till köksskärm", "Caféer, barer, food courts, lunchställen och restauranger med hög volym"],
      ["Menyskärmar (digital signage)", "TV-skärmar bakom disken med menyn, ofta i snabbmatsmiljö", "Quick service — men det är en helt annan produktkategori med hårdvarukostnad"],
    ]},
    { t: "p", text: "Servera är av typen webbmeny med valbar beställningsfunktion — du kan börja med enbart visning och slå på beställning per bord när du är redo. En djupare genomgång av skillnaderna mot papper finns i vår guide [digital meny vs tryckt meny](/guider/digital-meny-vs-tryckt)." },
    { t: "h2", id: "vad-kostar-det", text: "Vad kostar en digital meny?" },
    { t: "p", text: "Prismodellerna på den svenska marknaden faller i tre grupper: **fast månadspris** (typiskt 300–1 500 kr/mån beroende på funktioner och antal bord), **provision per beställning** (ofta 1–5 % av ordervärdet, vanligt hos internationella beställningsplattformar) och **gratisplaner** med begränsningar och leverantörens varumärke i din meny." },
    { t: "p", text: "Provisionsmodellen ser billig ut på papper men skalar med din omsättning: 3 % på en beställningsvolym om 300 000 kr/mån är 9 000 kr — mot en fast månadskostnad på under tusenlappen. Räkneexempel och en full marknadsjämförelse finns i [vad kostar en digital meny?](/guider/vad-kostar-digital-meny)" },
    { t: "p", text: "Som referens: [Serveras priser](/priser) är 549 kr/mån (Start, upp till 20 bord) och 999 kr/mån (Tillväxt, obegränsat antal bord), båda utan provision. Jämför det med tryckkostnaden för papper: hos tryckeriet Papperstryck kostar dubbelsidiga A4-menyer på 250 g papper ca 600 kr för 100 exemplar (6 kr/st) och 2 400 kr för 1 000 exemplar (2,40 kr/st) exklusive moms — per tryckning, varje gång menyn ändras." },
    { t: "callout", title: "Marginalerna pressas från två håll", text: "Enligt branschorganisationen Visitas restaurangrapport har restaurangernas råvarukostnader ökat med 37 % sedan februari 2022, medan priserna ut mot gäst bara ökat 19 %. Restaurangförsäljningen i volym minskade dessutom 1,5 % under 2024. I det läget är snabba prisjusteringar utan omtryckskostnad ett konkret verktyg — en digital meny låter dig justera priser samma dag som råvarupriset ändras." },
    { t: "h2", id: "lagkrav", text: "Vad säger lagen? Allergener, prisinformation och EU 1169/2011" },
    { t: "p", text: "Det finns inget lagkrav på att ha en digital meny — men det finns tydliga krav på **informationen** din meny ska kunna ge. Grunderna:" },
    { t: "ul", items: [
      "**Allergener:** EU:s livsmedelsinformationsförordning (EU) nr 1169/2011 pekar i bilaga II ut 14 allergener (bl.a. gluten, kräftdjur, ägg, fisk, jordnötter, soja, mjölk, nötter, selleri, senap, sesam, sulfiter, lupin och blötdjur) som alltid ska kunna redovisas — även för mat som serveras oförpackad på restaurang.",
      "**Hur informationen får ges:** Enligt Livsmedelsverkets föreskrifter (LIVSFS 2014:4, 8–11 §§) ska uppgifterna lämnas på begäran, och de får lämnas muntligt — men då måste det tydligt framgå för gästen hur hen får tillgång till uppgifterna, till exempel genom en skylt eller en tydlig rad i menyn.",
      "**Inga svepande friskrivningar:** Generella \"kan innehålla spår av allergener\"-texter utan koppling till en verklig, specifik risk accepteras inte som ersättning för korrekt allergeninformation.",
    ]},
    { t: "p", text: "En digital meny gör det praktiskt enkelt att ligga på rätt sida av kraven: allergenmärkningen ligger på varje rätt, uppdateras när receptet ändras, och gästen kan själv filtrera. I Servera märker du varje rätt med de vanliga allergenerna samt vegan/vegetariskt/glutenfritt, och informationen visas automatiskt för gästen. Muntlig dialog med personalen ersätts inte — gäster med allvarlig allergi ska alltid kunna stämma av med köket — men grundinformationen finns alltid framme." },
    { t: "h2", id: "skapa", text: "Hur skapar man en digital meny?" },
    { t: "p", text: "Själva uppsättningen är mindre jobb än de flesta tror — en meny med 40–60 rätter tar typiskt en eftermiddag att lägga in. Arbetsgången i korthet:" },
    { t: "ol", items: [
      "Samla menyn i ett dokument: rätter, beskrivningar, priser, allergener per rätt.",
      "Skapa konto hos din plattform och lägg in kategorier och rätter.",
      "Ladda upp bilder på de rätter som säljer bäst (bilder på allt behövs inte — men topprätterna förtjänar det).",
      "Generera och skriv ut QR-koder, en per bord om du vill ha bordskoppling.",
      "Testa hela flödet själv från en mobil innan gästerna gör det.",
    ]},
    { t: "p", text: "Hela processen, inklusive vanliga nybörjarmisstag och hur du testar innan lansering, finns i steg-för-steg-guiden [hur skapar man en digital meny?](/guider/hur-skapar-man-digital-meny)" },
    { t: "h2", id: "flersprakigt", text: "Behöver jag menyn på flera språk?" },
    { t: "p", text: "Om du har internationella gäster — turister, affärsresenärer, studenter — är svaret nästan alltid ja. En engelsk version är hygiennivån; i turisttäta lägen gör tyska, franska eller spanska verklig skillnad. Poängen med digital meny är att språkversionerna inte kräver separata tryckningar: gästen väljer språk själv, och du underhåller en enda meny. Hur du gör det bra — och inte pinsamt via automatöversättning av maträttsnamn — går vi igenom i [guiden om flerspråkig meny](/guider/flersprakig-meny)." },
    { t: "h2", id: "forsaljning", text: "Påverkar en digital meny försäljningen?" },
    { t: "p", text: "Här ska man vara ärlig med vad som är belagt och inte. Det finns tre mekanismer som talar för digital meny, och de är logiska snarare än magiska:" },
    { t: "ul", items: [
      "**Bilder och beskrivningar säljer.** Ett tryckt menykort har sällan plats för aptitretande bilder på varje rätt; en digital meny har det. Rätter med bild och bra beskrivning väljs oftare än anonyma rader.",
      "**Beställningströskeln sänks.** När gästen kan beställa påfyllning eller en dessert direkt från mobilen försvinner momentet \"vänta in personalens uppmärksamhet\" — beställningen som annars aldrig blivit av.",
      "**Menyn är alltid aktuell.** Slut på en rätt? Dölj den med ett klick i stället för att servera besvikelser. Nytt helgerbjudande? Ute på alla bord på en minut.",
    ]},
    { t: "p", text: "Vad du inte bör lita på är svepande påståenden om att \"digital meny ökar snittnotan med X %\" utan källa. Effekten beror på din servering, dina gäster och hur bra menyn är gjord. Mät själv: Servera visar visningar och beställningar per rätt, så att du ser vad som faktiskt händer efter bytet." },
    { t: "h2", id: "vanliga-misstag", text: "Vilka är de vanligaste misstagen?" },
    { t: "ul", items: [
      "**PDF:en som \"digital meny\".** En PDF bakom en QR-kod är tekniskt sett digital, men gästupplevelsen på mobil är dålig och allergenfiltrering saknas. Se det som en tillfällig lösning, inte en digital meny.",
      "**QR-koder utan sammanhang.** En kod på bordet utan text. Skriv alltid en rad: \"Skanna för meny & beställning\" — och ha tryckta reservmenyer för gäster som inte vill eller kan använda mobilen.",
      "**Ingen ansvarig för menyn.** Utse en person som äger menyinnehållet. Den största vinsten med digital meny — att den alltid är aktuell — förverkligas bara om någon faktiskt uppdaterar den.",
      "**Att låsa in sig i provisioner.** Läs prislistan noga: 1–5 % per order låter lite men blir den största posten när volymen växer.",
      "**Glömma allergenerna.** Att flytta menyn till mobilen tar inte bort informationskraven — men rätt gjort blir de enklare att uppfylla, inte svårare.",
    ]},
    { t: "h2", id: "checklista", text: "Checklista: att kräva av en digital meny-plattform 2026" },
    { t: "ul", items: [
      "Ingen app-nedladdning för gästen — menyn öppnas i webbläsaren.",
      "Allergenmärkning per rätt, synlig för gästen utan att fråga.",
      "Priser i SEK, fast månadskostnad, ingen provision per beställning.",
      "Beställningsfunktion som kan slås på när du är redo — inte ett tvång från dag ett.",
      "Flerspråksstöd där du kontrollerar översättningarna.",
      "Fungerar ihop med ditt befintliga kassasystem — du ska inte behöva byta kassa för menyns skull.",
      "Statistik: mest visade rätter, beställningar per bord, per tid på dygnet.",
      "Svensk support och GDPR-hantering inom EU.",
    ]},
    { t: "p", text: "Vill du se hur Servera löser punkterna ovan — [boka en demo](/#contact) eller titta på [så fungerar det](/sa-fungerar-det). Vill du jämföra oss med alternativen först är [jämförelsesidan](/jamfor) rätt ställe att börja." },
  ],
  faq: [
    { question: "Vad är en digital meny?", answer: "En digital meny är en restaurangmeny som gästen läser på en skärm i stället för på papper — oftast i sin egen mobil via en QR-kod på bordet. Moderna digitala menyer öppnas direkt i webbläsaren utan app och kan visa bilder, allergener och priser, och i många system även ta emot beställningar." },
    { question: "Måste gästen ladda ned en app?", answer: "Nej. Standarden i Sverige 2026 är app-fria menyer som öppnas direkt i mobilens webbläsare när gästen skannar QR-koden. Undvik lösningar som kräver app-nedladdning — de tappar gäster redan innan menyn visats." },
    { question: "Vad kostar en digital meny i Sverige?", answer: "Typiskt några hundralappar i månaden i fast kostnad. Servera kostar 549 kr/mån (upp till 20 bord) eller 999 kr/mån (obegränsat), utan provision. Provisionsbaserade alternativ tar i stället ofta 1–5 % per beställning, vilket blir dyrare vid högre volym." },
    { question: "Är digital meny ett lagkrav?", answer: "Nej, men informationen menyn ger regleras: allergeninformation för de 14 allergenerna i EU-förordning 1169/2011 ska alltid kunna lämnas, och lämnas den muntligt måste det tydligt framgå hur gästen får tag på den (LIVSFS 2014:4). En digital meny med allergenmärkning per rätt gör det enkelt att uppfylla kraven." },
    { question: "Fungerar digital meny utan internet?", answer: "Gästens mobil behöver internetuppkoppling (wifi eller mobilnät) för att öppna menyn, och köksvyn behöver uppkoppling för att ta emot beställningar. Ha alltid några tryckta reservmenyer för gäster utan fungerande mobil." },
    { question: "Kan jag ha kvar tryckta menyer samtidigt?", answer: "Ja, och det är ofta klokt. Många restauranger kör digital meny som primär lösning och ett mindre antal tryckta exemplar för gäster som föredrar papper. Se bara till att den tryckta versionen inte blir liggande inaktuell när den digitala uppdateras." },
  ],
  sources: [
    { label: "Europaparlamentets och rådets förordning (EU) nr 1169/2011 om livsmedelsinformation (bilaga II: allergener)", href: "https://eur-lex.europa.eu/legal-content/SV/TXT/?uri=CELEX%3A02011R1169-20180101" },
    { label: "Livsmedelsverkets föreskrifter om livsmedelsinformation, LIVSFS 2014:4", href: "https://www.livsmedelsverket.se/om-oss/lagstiftning1/gallande-lagstiftning/livsfs-20144" },
    { label: "Visita: Den svenska restaurangmarknaden — K4 2024 och K1 2025", href: "https://visita.se/app/uploads/2025/06/Restaurangrapport-K4-2024-och-K1-2025.pdf" },
    { label: "Papperstryck: priser för tryckta menyer", href: "https://www.papperstryck.se/menyer/" },
  ],
}
