import type { Guide } from "./types"

export const guide: Guide = {
  slug: "hur-skapar-man-digital-meny",
  title: "Hur skapar man en digital meny? Steg för steg",
  metaTitle: "Hur skapar man en digital meny? Steg för steg-guide",
  description:
    "Skapa en digital meny för din restaurang på en eftermiddag: förbered innehållet, lägg in rätter och allergener, generera QR-koder per bord och testa innan lansering.",
  datePublished: "2026-08-26",
  dateModified: "2026-08-26",
  readingMinutes: 8,
  category: "Steg för steg",
  intro: [
    "Att skapa en digital meny betyder i praktiken tre saker: strukturera menyinnehållet, lägga in det i en menyplattform och sätta QR-koder på borden. För en meny med 40–60 rätter tar hela jobbet ungefär en eftermiddag — förutsatt att du förbereder innehållet innan du sätter dig i verktyget.",
    "Den här guiden går igenom varje steg i ordning, med de fällor som brukar kosta mest tid. Den utgår från [Servera](/sa-fungerar-det) men stegen är desamma oavsett plattform.",
  ],
  tldr: [
    "Förbered allt innehåll i ett dokument först — rätter, priser, beskrivningar, allergener. Det är 80 % av jobbet.",
    "Lägg in kategorier före rätter, och märk allergener direkt när du lägger in varje rätt — inte som ett \"sen\"-projekt.",
    "Använd en unik QR-kod per bord om du vill ta emot beställningar; en gemensam kod räcker för ren visning.",
    "Testa hela flödet på en egen mobil (och en kollegas Android/iPhone) innan gästerna släpps på.",
    "Utse en menyansvarig — den största vinsten är att menyn alltid är aktuell, och det kräver en ägare.",
  ],
  blocks: [
    { t: "h2", id: "steg-1", text: "Steg 1: Förbered innehållet innan du öppnar verktyget" },
    { t: "p", text: "Det vanligaste misstaget är att börja klicka i adminpanelen med menyn i huvudet. Gör tvärtom: samla allt i ett dokument först. För varje rätt behöver du:" },
    { t: "ul", items: [
      "**Namn** — som gästen känner igen det, inte köksslang.",
      "**Beskrivning** — en eller två meningar. Skriv vad gästen får, inte poesi: \"Långbakad högrev, potatispuré, rostade morötter, rödvinssky\" slår \"En smakresa i höstens tecken\".",
      "**Pris** — och bestäm samtidigt vem som får ändra priser framöver.",
      "**Allergener** — gå igenom rätt för rätt mot de 14 allergenerna i EU-förordningen (gluten, kräftdjur, ägg, fisk, jordnötter, soja, mjölk, nötter, selleri, senap, sesam, sulfiter, lupin, blötdjur). Fråga köket, gissa aldrig.",
      "**Kategori** — förrätter, varmrätter, pizza, dryck osv. Max ~8 kategorier; fler gör mobilnavigeringen sämre.",
    ]},
    { t: "callout", title: "Allergenerna är inte valfria", text: "Allergeninformation ska alltid kunna lämnas för oförpackad mat som serveras på restaurang, enligt EU-förordning 1169/2011 och Livsmedelsverkets föreskrifter LIVSFS 2014:4. Ges den muntligt måste det tydligt framgå hur gästen får tag på den. När du ändå lägger in menyn digitalt: märk varje rätt direkt, så är saken ur världen." },
    { t: "h2", id: "steg-2", text: "Steg 2: Lägg in kategorier och rätter" },
    { t: "p", text: "Skapa kategorierna först, i den ordning gästen ska möta dem — de flesta plattformar visar kategorierna som flikar eller sektioner uppifrån och ned. Lägg sedan in rätterna kategori för kategori. Med förarbetet från steg 1 är det ren inmatning; räkna med 1–2 minuter per rätt." },
    { t: "p", text: "Ordningen inom varje kategori spelar roll: gäster läser menyer som listor, och de första positionerna får flest blickar. Lägg rätterna du helst säljer — bäst marginal, kökets stolthet — överst, inte i bokstavsordning." },
    { t: "h2", id: "steg-3", text: "Steg 3: Bilder — på rätt rätter" },
    { t: "p", text: "Du behöver inte fota allt. Prioritera: signaturrätter, desserter och det du vill sälja mer av. En bra bild tas i dagsljus, uppifrån eller i 45 graders vinkel, på en riktig tallrik ur din servering — inte stockfoton, som gäster genomskådar direkt och som dessutom kan ge fel förväntningar." },
    { t: "p", text: "Hoppa hellre över bilden än att använda en dålig: en mörk, gulstichig köksbild säljer sämre än ingen bild alls." },
    { t: "h2", id: "steg-4", text: "Steg 4: Generera QR-koder och koppla dem till borden" },
    { t: "p", text: "Här skiljer sig två upplägg åt:" },
    { t: "table", head: ["Upplägg", "Hur det fungerar", "När det passar"], rows: [
      ["En gemensam QR-kod", "Alla bord får samma kod som öppnar menyn", "Ren menyvisning utan beställning, food trucks, barhäng"],
      ["Unik kod per bord", "Koden identifierar bordet — beställningar kopplas automatiskt rätt", "Beställning från bordet, notor per bord, statistik per bord"],
    ]},
    { t: "p", text: "I Servera genereras bordskoderna automatiskt och kan skrivas ut direkt. Praktiska råd för det fysiska: laminera korten eller använd bordsställ, sätt koden där den inte täcks av tallrikar, och skriv alltid en rad text vid koden — \"Skanna för meny & beställning\". En naken QR-kod utan förklaring skapar tvekan." },
    { t: "h2", id: "steg-5", text: "Steg 5: Testa som gäst innan lansering" },
    { t: "p", text: "Innan du släpper på gästerna, gå igenom hela flödet själv — och gör det på mer än en telefon, gärna både iPhone och Android:" },
    { t: "ol", items: [
      "Skanna koden från ett bord. Öppnas menyn snabbt på mobilnät, inte bara på wifi?",
      "Bläddra genom varje kategori. Är ordningen rätt? Saknas något? Stavfel?",
      "Kontrollera allergenmärkningen på fem slumpade rätter mot kökets facit.",
      "Lägg en testbeställning (om beställning är på) och se att den landar i köksvyn.",
      "Be någon som inte varit med i uppsättningen — en i personalen, en stamgäst — göra samma sak och säga vad som är otydligt.",
    ]},
    { t: "h2", id: "steg-6", text: "Steg 6: Lansera — och utse en menyansvarig" },
    { t: "p", text: "Själva lanseringen är odramatisk: lägg ut korten på borden. Det som avgör om satsningen bär sig är vad som händer veckorna efter. Utse en person som äger menyn: prisändringar, slut-i-kök-markeringar, nya rätter, säsongsbyten. En digital meny som inte underhålls är bara en snyggare version av det inaktuella menykortet." },
    { t: "p", text: "Titta också på statistiken efter ett par veckor: vilka rätter visas mest men beställs sällan (fel pris? fel beskrivning?), och vilka beställs mest (lyft dem högre). Det är data du aldrig fick av papperskortet." },
    { t: "h2", id: "hur-lang-tid", text: "Hur lång tid tar det totalt?" },
    { t: "table", head: ["Moment", "Tidsåtgång"], rows: [
      ["Förbereda innehåll (steg 1)", "2–4 timmar för 40–60 rätter"],
      ["Inmatning i plattformen", "1–2 timmar"],
      ["Bilder på topprätter", "1 timme (görs löpande)"],
      ["QR-koder och utplacering", "30 minuter"],
      ["Test", "30 minuter"],
    ]},
    { t: "p", text: "Med andra ord: en eftermiddag för en normalstor meny, med förarbetet som största post. Vill du se hur det ser ut i praktiken — [boka en demo av Servera](/#contact), eller läs [kompletta guiden om digital meny](/guider/digital-meny-kompletta-guiden) om du fortfarande jämför alternativ." },
  ],
  faq: [
    { question: "Hur lång tid tar det att skapa en digital meny?", answer: "Ungefär en eftermiddag för en meny med 40–60 rätter: 2–4 timmar för att förbereda innehåll (rätter, priser, allergener), 1–2 timmar inmatning, plus en halvtimme vardera för QR-koder och test." },
    { question: "Behöver jag bilder på alla rätter?", answer: "Nej. Prioritera signaturrätter, desserter och rätter du vill sälja mer av. En dålig bild är sämre än ingen bild — fota i dagsljus på riktiga tallrikar ur din egen servering och undvik stockfoton." },
    { question: "Ska jag ha en QR-kod per bord eller en gemensam?", answer: "Vill du bara visa menyn räcker en gemensam kod. Vill du ta emot beställningar från bordet behöver du en unik kod per bord, så att ordrar kopplas till rätt bord automatiskt." },
    { question: "Hur hanterar jag allergener i en digital meny?", answer: "Gå igenom varje rätt mot de 14 allergenerna i EU-förordning 1169/2011 tillsammans med köket och märk rätten i systemet när du lägger in den. Informationen visas då automatiskt för gästen, och du uppfyller kravet på att allergeninformation ska finnas tillgänglig." },
    { question: "Kan jag ändra menyn efter lansering?", answer: "Ja — det är hela poängen. Prisändringar, slutsålda rätter och säsongsbyten slår igenom direkt på alla bord. Utse en menyansvarig så att uppdateringarna faktiskt blir gjorda." },
  ],
  sources: [
    { label: "Europaparlamentets och rådets förordning (EU) nr 1169/2011 om livsmedelsinformation (bilaga II: allergener)", href: "https://eur-lex.europa.eu/legal-content/SV/TXT/?uri=CELEX%3A02011R1169-20180101" },
    { label: "Livsmedelsverkets föreskrifter om livsmedelsinformation, LIVSFS 2014:4", href: "https://www.livsmedelsverket.se/om-oss/lagstiftning1/gallande-lagstiftning/livsfs-20144" },
  ],
}
